version: '3.6'

services:
    nginx:
        container_name: nginx_${PROJECT_USER}
        build:
            context: ./misc/dockerfiles/nginx
            dockerfile: Dockerfile
        ports:
            - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
        volumes:
            - .:/var/www/html
        links:
            - website
        networks:
            - backend
        depends_on:
            - website
        restart: always
    website:
        container_name: website_${PROJECT_USER}
        build:
            context: ./misc/dockerfiles/php
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        networks:
            - backend
        restart: always

networks:
    backend: