version: '3.6'

services:
    database:
        container_name: database_${PROJECT_USER}
        image: mysql:5.6
        ports:
            - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
        env_file:
            - .env
        volumes:
            - ./misc/bin:/bin/init_database/scripts/
            - ./artifacts/templates:/bin/init_database/templates/
        networks:
            - backend
    nginx:
        container_name: nginx_${PROJECT_USER}
        build:
            context: ./misc/dockerfiles/nginx
            dockerfile: Dockerfile
        ports:
            - ${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}
        volumes:
            - .:/var/www/html
        links:
            - api
        networks:
            - backend
        depends_on:
            - api
        restart: always
    api:
        container_name: api_${PROJECT_USER}
        build:
            context: ./misc/dockerfiles/php
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        networks:
            - backend
    python:
        container_name: python_${PROJECT_USER}
        build:
            context: ./misc/dockerfiles/python
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - .:/App/code
        networks:
            - backend

networks:
    backend:
