openapi: 3.0.0
info:
  title: CKM Timing API
  version: 1.0.0
tags:
- name: System
  description: Endpoints of system health and configuration.
- name: Events
  description: Information about available events.
- name: Santos Endurance Events
  description: Endpoints for endurance events in Karting Los Santos.
paths:
  /validate-token:
    get:
      summary: Validates whether the X-Request-ID token is valid or not.
      tags:
      - System
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
  /events:
    get:
      summary: Returns list of available events to monitor.
      tags:
      - Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/SantosEnduranceEvent'
    post:
      summary: Creates a new event.
      tags:
      - Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SantosEnduranceEventSimple'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
  /events/{event-id}/stats:
    get:
      summary: Returns the current stats of the event.
      tags:
      - Santos Endurance Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventStat'
  /events/{event-id}/stats/{stat-name}:
    put:
      summary: Updates the value of a specific stat.
      tags:
      - Santos Endurance Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventStatSimple'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
  /events/{event-id}/timing:
    post:
      summary: Adds a lap time of a driver/team in the event.
      tags:
      - Santos Endurance Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimingItem'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
  /events/{event-id}/timing/all/{timing-type}:
    get:
      summary: Returns the live timing information with the real positions.
      tags:
      - Santos Endurance Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      - name: timing-type
        in: path
        required: true
        description: If "onlap", it returns the live timing positions. If "real", it returns the positions taking into account the remaining stops.
        schema:
          type: string
          enum: ['onlap', 'real']
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      ranking:
                        type: array
                        items:
                          $ref: '#/components/schemas/RankingPosition'
  /events/{event-id}/timing/teams:
    get:
      summary: Returns the teams and their data.
      tags:
      - Santos Endurance Events
      parameters:
      - $ref: '#/components/parameters/HeaderRequestID'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
  /events/{event-id}/health:
    get:
      summary: Returns health of components of backend.
      tags:
      - Santos Endurance Events
      parameters:
        - $ref: '#/components/parameters/HeaderRequestID'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      categories:
                        type: object
                        properties:
                          event:
                            $ref: '#/components/schemas/HealthCategory'
                          database:
                            $ref: '#/components/schemas/HealthCategory'
                          crawler:
                            $ref: '#/components/schemas/HealthCategory'
                          batches:
                            $ref: '#/components/schemas/HealthCategory'
                      items:
                        type: object
                        properties:
                          event_status:
                            $ref: '#/components/schemas/HealthItem'
                          event_stage:
                            $ref: '#/components/schemas/HealthItem'
                          database_connection:
                            $ref: '#/components/schemas/HealthItem'
                          crawler_internet:
                            $ref: '#/components/schemas/HealthItem'
                          crawler_apex:
                            $ref: '#/components/schemas/HealthItem'
                          crawler_parse_teams:
                            $ref: '#/components/schemas/HealthItem'
                          crawler_parse_drivers:
                            $ref: '#/components/schemas/HealthItem'
                          crawler_parse_timing:
                            $ref: '#/components/schemas/HealthItem'
                          batch_karts_box_probs:
                            $ref: '#/components/schemas/HealthItem'
                          batch_karts_status:
                            $ref: '#/components/schemas/HealthItem'
                          batch_time_references:
                            $ref: '#/components/schemas/HealthItem'
  /events/{event-id}/health/{health-category}/{health-name}:
    put:
      summary: Updates the status of an element.
      tags:
      - Santos Endurance Events
      parameters:
        - $ref: '#/components/parameters/HeaderRequestID'
        - name: health-category
          in: path
          required: true
          description: Category of the health item.
          schema:
            type: string
        - name: health-name
          in: path
          required: true
          description: Name of the health item.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthItemSimple'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HealthItem'

components:
  parameters:
    HeaderRequestID:
      in: header
      name: X-Request-ID
      description: Works as auth token to use the API endpoints.
      schema:
        type: string
      required: true
  schemas:
    SantosEnduranceEvent:
      allOf:
      - type: object
        properties:
          id:
            type: string
      - $ref: '#/components/schemas/SantosEnduranceEventSimple'
    SantosEnduranceEventSimple:
      type: object
      properties:
        track_name:
          type: string
          enum: [santos]
          example: santos
        race_type:
          type: string
          enum: [endurance]
          example: endurance
        race_length:
          type: integer
          example: 3
        race_length_unit:
          type: string
          enum: [laps, hours]
          example: hours
        reference_time_top_teams:
          type: integer
          example: 10
    TimingItem:
      type: object
      properties:
        position:
          type: integer
          minimum: 1
        team_name:
          type: string
        driver_name:
          type: string
        time:
          type: integer
        gap:
          type: integer
    RankingPosition:
      type: object
      properties:
        position:
          type: integer
          minimum: 1
        team_name:
          type: string
        driver_name:
          type: string
        best_time:
          type: integer
        last_time:
          type: integer
        kart_status:
          type: string
          enum: ['unknown', 'good', 'medium', 'bad']
        kart_status_guess:
          type: string
          enum: ['good', 'medium', 'bad']
        forced_status:
          type: boolean
        update_date:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
    HealthCategory:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
    HealthItem:
      allOf:
      - type: object
        properties:
          category:
            type: string
          name:
            type: string
          update_date:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
      - $ref: '#/components/schemas/HealthItemSimple'
    HealthItemSimple:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    EventStat:
      allOf:
      - type: object
        properties:
          name:
            type: string
          update_date:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
      - $ref: '#/components/schemas/EventStatSimple'
    EventStatSimple:
      type: object
      properties:
        value:
          type: string
